apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: azure-postgresql-alerts
  namespace: observability
  labels:
    prometheus: kube-prometheus
    role: alert-rules
    app.kubernetes.io/name: copperiq-monitoring
    app.kubernetes.io/component: alert-rules
spec:
  groups:
    - name: azure-postgresql
      interval: 1m
      rules:
        # Note: These alerts use Azure Monitor metrics via Grafana Azure Monitor datasource
        # Metrics are typically available as: azure_postgresql_flexible_server_<metric_name>
        # Adjust metric names based on your actual Azure Monitor integration

        - alert: AzurePostgreSQLHighCPU
          expr: |
            azure_postgresql_flexible_server_cpu_percent > 80
          for: 10m
          labels:
            severity: warning
            component: postgresql
            category: azure-resources
          annotations:
            summary: "PostgreSQL server {{ $labels.server_name }} CPU > 80%"
            description: |
              Azure PostgreSQL Flexible Server {{ $labels.server_name }} CPU usage is {{ $value }}%.
              
              **Databases affected**: n8n-data-shared-dev, n8n-data-shared-prod, langfuse, content-platform
              
              **Impact**: Query performance degradation, slower response times.
              
              **Action**:
              1. Check slow queries in Azure Portal: Monitor → Insights → Query Performance Insight
              2. Review active connections and long-running queries
              3. Consider scaling up if sustained
              4. Check for inefficient queries or missing indexes
            runbook_url: "https://github.com/Copper-IQ/copperiq-monitoring/blob/main/docs/runbooks/azure-postgresql-high-cpu.md"

        - alert: AzurePostgreSQLCriticalCPU
          expr: |
            azure_postgresql_flexible_server_cpu_percent > 95
          for: 5m
          labels:
            severity: critical
            component: postgresql
            category: azure-resources
          annotations:
            summary: "PostgreSQL server {{ $labels.server_name }} CPU > 95% - CRITICAL"
            description: |
              CRITICAL: Azure PostgreSQL server {{ $labels.server_name }} CPU at {{ $value }}%.
              
              **Immediate action required**:
              1. Identify blocking queries: Check pg_stat_activity
              2. Kill long-running queries if safe
              3. Scale up database tier immediately
              4. Check for deadlocks or lock contention

        - alert: AzurePostgreSQLHighMemory
          expr: |
            azure_postgresql_flexible_server_memory_percent > 85
          for: 10m
          labels:
            severity: warning
            component: postgresql
            category: azure-resources
          annotations:
            summary: "PostgreSQL server {{ $labels.server_name }} memory > 85%"
            description: |
              Azure PostgreSQL memory usage at {{ $value }}%.
              
              **Impact**: Risk of OOM, query failures, connection issues.
              
              **Action**:
              1. Check memory usage in Azure Portal
              2. Review connection pool sizes (n8n, content-platform configs)
              3. Check for memory leaks in prepared statements
              4. Consider scaling up memory tier

        - alert: AzurePostgreSQLStorageNearFull
          expr: |
            azure_postgresql_flexible_server_storage_percent > 80
          for: 5m
          labels:
            severity: warning
            component: postgresql
            category: azure-resources
          annotations:
            summary: "PostgreSQL server {{ $labels.server_name }} storage > 80% full"
            description: |
              Azure PostgreSQL storage is {{ $value }}% full.
              
              **Impact**: Risk of write failures, database unavailability.
              
              **Action**:
              1. Check storage growth trend in Azure Portal
              2. Identify largest tables: `SELECT schemaname, tablename, pg_total_relation_size(schemaname||'.'||tablename) FROM pg_tables ORDER BY 3 DESC LIMIT 10;`
              3. Clean up old data if applicable
              4. Enable auto-grow or manually increase storage

        - alert: AzurePostgreSQLStorageCritical
          expr: |
            azure_postgresql_flexible_server_storage_percent > 90
          for: 2m
          labels:
            severity: critical
            component: postgresql
            category: azure-resources
          annotations:
            summary: "PostgreSQL server {{ $labels.server_name }} storage > 90% CRITICAL"
            description: |
              CRITICAL: Storage {{ $value }}% full. Write failures imminent.
              
              **Immediate action**:
              1. Increase storage size in Azure Portal immediately
              2. Pause non-critical writes if possible
              3. Archive or delete old data urgently
              4. Check for runaway log growth

        - alert: AzurePostgreSQLHighConnections
          expr: |
            (azure_postgresql_flexible_server_active_connections / azure_postgresql_flexible_server_connections_limit) * 100 > 80
          for: 5m
          labels:
            severity: warning
            component: postgresql
            category: azure-resources
          annotations:
            summary: "PostgreSQL server {{ $labels.server_name }} connections > 80% of limit"
            description: |
              Active connections: {{ $value }}% of max limit.
              
              **Impact**: New connections may be rejected, application errors.
              
              **Action**:
              1. Check active connections: `SELECT count(*) FROM pg_stat_activity;`
              2. Identify connection sources: `SELECT usename, application_name, count(*) FROM pg_stat_activity GROUP BY 1,2;`
              3. Review connection pool settings in n8n and content-platform
              4. Check for connection leaks (connections not being released)
              5. Consider increasing max_connections or connection pooling

        - alert: AzurePostgreSQLFailedConnections
          expr: |
            rate(azure_postgresql_flexible_server_connections_failed_total[5m]) > 10
          for: 5m
          labels:
            severity: warning
            component: postgresql
            category: azure-resources
          annotations:
            summary: "PostgreSQL server {{ $labels.server_name }} experiencing failed connections"
            description: |
              {{ $value }} failed connections per minute.
              
              **Possible causes**:
              1. Authentication failures
              2. Network connectivity issues
              3. Firewall rules blocking connections
              4. SSL certificate issues
              
              **Action**:
              1. Check Azure firewall rules
              2. Verify credentials in application configs
              3. Check VNet/subnet configuration
              4. Review PostgreSQL logs in Azure Portal

        - alert: AzurePostgreSQLReplicationLag
          expr: |
            azure_postgresql_flexible_server_replication_lag_seconds > 60
          for: 5m
          labels:
            severity: warning
            component: postgresql
            category: azure-resources
          annotations:
            summary: "PostgreSQL replication lag > 60 seconds"
            description: |
              Replication lag is {{ $value }} seconds (if HA/read replicas configured).
              
              **Impact**: Stale reads from replicas, HA failover delay.
              
              **Action**:
              1. Check replica status in Azure Portal
              2. Verify network connectivity to replica
              3. Check for long-running transactions blocking replication
              4. Review write load on primary

        - alert: AzurePostgreSQLBackupFailed
          expr: |
            azure_postgresql_flexible_server_backup_storage_used_bytes == 0
          for: 1h
          labels:
            severity: critical
            component: postgresql
            category: azure-resources
          annotations:
            summary: "PostgreSQL server {{ $labels.server_name }} backup may be failing"
            description: |
              No backup storage usage detected for 1 hour.
              
              **Impact**: Data loss risk if server fails.
              
              **Action**:
              1. Check backup status in Azure Portal: Backup and Restore blade
              2. Verify backup policy is configured
              3. Check for backup errors in Activity Log
              4. Open support ticket if backups are actually failing
