apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: node-disk-space-alerts
  namespace: observability
  labels:
    prometheus: kube-prometheus
    role: alert-rules
    app.kubernetes.io/name: copperiq-monitoring
    app.kubernetes.io/component: alert-rules
spec:
  groups:
    - name: node-disk-space
      interval: 30s
      rules:
        - alert: NodeDiskSpaceWarning
          expr: |
            (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) < 0.25
          for: 5m
          labels:
            severity: warning
            component: aks
            category: infrastructure
          annotations:
            summary: "Node {{ $labels.node }} disk > 75% full"
            description: |
              Node {{ $labels.node }} has less than 25% disk space available ({{ $value | humanizePercentage }} free).
              
              **Likely cause**: Unpruned Docker images accumulating on the node.
              
              **Impact**: ImageGC will start at 85%, may cause pod evictions.
              
              **Action**: 
              1. Check image cache size: `crictl images`
              2. Manually prune if needed: `crictl rmi --prune`
              3. Consider automated image pruning policy
            runbook_url: "https://github.com/Copper-IQ/copperiq-monitoring/blob/main/docs/runbooks/node-disk-space-critical.md"

        - alert: NodeDiskSpaceCritical
          expr: |
            (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) < 0.15
          for: 2m
          labels:
            severity: critical
            component: aks
            category: infrastructure
          annotations:
            summary: "Node {{ $labels.node }} disk > 85% full - CRITICAL"
            description: |
              Node {{ $labels.node }} has less than 15% disk space available ({{ $value | humanizePercentage }} free).
              
              **CRITICAL**: ImageGC threshold reached. Pod evictions imminent.
              
              **Immediate action required**:
              1. Identify largest images: `crictl images | sort -k7 -h`
              2. Force prune unused images: `crictl rmi --prune`
              3. Check for large container layers: `du -sh /var/lib/containerd/*`
              4. Monitor pod evictions: `kubectl get events --field-selector reason=Evicted`
            runbook_url: "https://github.com/Copper-IQ/copperiq-monitoring/blob/main/docs/runbooks/node-disk-space-critical.md"

        - alert: NodeEphemeralStorageHigh
          expr: |
            (1 - (node_filesystem_avail_bytes{mountpoint=~"/var/lib/(docker|containerd)"} / node_filesystem_size_bytes{mountpoint=~"/var/lib/(docker|containerd)"})) > 0.8
          for: 10m
          labels:
            severity: warning
            component: aks
            category: infrastructure
          annotations:
            summary: "Node {{ $labels.node }} ephemeral storage > 80%"
            description: |
              Container runtime storage on node {{ $labels.node }} is {{ $value | humanizePercentage }} full.
              
              **Cause**: Container layer accumulation in {{ $labels.mountpoint }}.
              
              **Action**:
              1. Check container disk usage: `crictl stats`
              2. Inspect stopped containers: `crictl ps -a --state Exited`
              3. Remove stopped containers: `crictl rm $(crictl ps -a -q --state Exited)`
            runbook_url: "https://github.com/Copper-IQ/copperiq-monitoring/blob/main/docs/runbooks/node-disk-space-critical.md"
